'use strict';
const $=id=>document.getElementById(id), KEY='passive-ammeter-records-v1';
let scan=null, records=JSON.parse(localStorage.getItem(KEY)||'[]'), meters=new Map();
for(let i=0;i<16;i++) $('address').add(new Option(i.toString(16).toUpperCase(),i.toString(16).toUpperCase()));
function crc8(s){let c=0;for(const ch of s){c^=ch.charCodeAt(0);for(let b=0;b<8;b++)c=(c&128)?((c<<1)^7)&255:(c<<1)&255}return c}
function parse(text){const m=text.match(/M1[0-9A-F][0-9]{4}[0-9A-F]{3}[0-9A-F]{2}/i);if(!m)return null;const f=m[0].toUpperCase();if(crc8(f.slice(0,10))!==parseInt(f.slice(10),16))return null;return{address:f[2],mA:+f.slice(3,7),flags:parseInt(f[7],16),seq:parseInt(f.slice(8,10),16)}}
function bytesText(view){return new TextDecoder().decode(new Uint8Array(view.buffer,view.byteOffset,view.byteLength))}
function eventFrames(e){const out=[];if(e.device?.name)out.push(e.device.name);for(const map of [e.manufacturerData,e.serviceData])if(map)for(const v of map.values())out.push(bytesText(v));return out}
function statusOf(m,offline=false){if(offline)return'OFFLINE';if(m.flags&4)return'ERROR';if(m.flags&8)return'UNCAL';if(m.mA<200||m.flags&1)return'LOW';if(m.mA>2000||m.flags&2)return'HIGH';return'NORMAL'}
function accept(m){if($('mode').value==='basic'&&m.address!==$('address').value)return;const now=Date.now(),old=meters.get(m.address);m.time=now;m.saved=old?.saved||0;if(!old||now-m.saved>=120000){m.saved=now;records.push({time:now,address:m.address,mA:m.mA,state:statusOf(m)});if(records.length>500)records=records.slice(-500);localStorage.setItem(KEY,JSON.stringify(records))}meters.set(m.address,m);render()}
function onAdv(e){for(const text of eventFrames(e)){const m=parse(text);if(m){accept(m);break}}}
async function start(){if(!navigator.bluetooth)throw Error('此浏览器不支持 Web Bluetooth');if(navigator.bluetooth.requestLEScan){scan=await navigator.bluetooth.requestLEScan({acceptAllAdvertisements:true,keepRepeatedDevices:true});navigator.bluetooth.addEventListener('advertisementreceived',onAdv)}else{const d=await navigator.bluetooth.requestDevice({acceptAllDevices:true,optionalServices:[0xffe0]});d.addEventListener('advertisementreceived',onAdv);await d.watchAdvertisements();scan=d} $('scan').textContent='扫描中'}
function stop(){if(scan?.stop)scan.stop();navigator.bluetooth?.removeEventListener('advertisementreceived',onAdv);scan=null;$('scan').textContent='开始扫描'}
function render(){const wanted=$('mode').value==='basic'?meters.get($('address').value):[...meters.values()].sort((a,b)=>b.time-a.time)[0];if(wanted){const off=Date.now()-wanted.time>10000,s=statusOf(wanted,off);$('current').textContent=(wanted.mA/1000).toFixed(3)+' A';$('state').textContent=s;$('state').className=s==='NORMAL'?'ok':s.toLowerCase();$('detail').textContent=`地址 ${wanted.address}  V1  序号 ${wanted.seq}  ${new Date(wanted.time).toLocaleTimeString()}`}else{$('current').textContent='-- A';$('state').textContent='未发现';$('state').className='offline'}
  $('rows').innerHTML=records.slice(-100).reverse().map(r=>`<tr><td>${new Date(r.time).toLocaleString()}</td><td>${r.address}</td><td>${(r.mA/1000).toFixed(3)}</td><td>${r.state}</td></tr>`).join('');draw()}
function draw(){const c=$('trend'),x=c.getContext('2d'),a=$('address').value,p=records.filter(r=>r.address===a).slice(-60);x.clearRect(0,0,c.width,c.height);x.strokeStyle='#cad8e2';x.beginPath();for(let y=20;y<c.height;y+=40){x.moveTo(0,y);x.lineTo(c.width,y)}x.stroke();if(p.length<2)return;const max=Math.max(2100,...p.map(v=>v.mA));x.strokeStyle='#1261a0';x.lineWidth=3;x.beginPath();p.forEach((v,i)=>{const px=i*c.width/(p.length-1),py=c.height-10-v.mA*(c.height-20)/max;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
$('scan').onclick=()=>start().catch(e=>alert(e.message));$('stop').onclick=stop;$('mode').onchange=render;$('address').onchange=render;
$('clear').onclick=()=>{if(confirm('清空手机中的全部记录？')){records=[];localStorage.removeItem(KEY);render()}};
$('csv').onclick=()=>{const s='time,address,current_A,status\n'+records.map(r=>`${new Date(r.time).toISOString()},${r.address},${(r.mA/1000).toFixed(3)},${r.state}`).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s],{type:'text/csv'}));a.download='ammeter.csv';a.click()};
setInterval(render,1000);render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
